### ISSUE TITLE
[BUG]: ETag fix has caused feed retrieval issues on certain sites

### ISSUE THREAD

**Issue by ImportTaste** [martinrotter/rssguard#1314]
### Brief description of the issue

>> @martinrotter closed #1296 as completed in https://github.com/martinrotter/rssguard/commit/eb6332cc5c473d6056bd6d9e011017129942ec7d

>>> _Originally posted by @guihkx at https://github.com/martinrotter/rssguard/issues/1296#issuecomment-1956574185_ in 
>>
>> Confirming fixed, thanks!
>>
>> ```
>> time="    35.521" type="debug" -> core: Downloading URL 'https://thisweek.gnome.org/index.xml' to obtain feed data.
>> time="    35.521" type="debug" -> Using ETag value: '"c8ec4932421ffe7f0bf6994837a53762a9c85f37c73c575ddaf7774d2c390617"'.
>> ```
>>
>> ```
>> $ curl -sI https://thisweek.gnome.org/index.xml | grep -i etag
>> etag: "c8ec4932421ffe7f0bf6994837a53762a9c85f37c73c575ddaf7774d2c390617"
>> ```

The fix for this issue (https://github.com/martinrotter/rssguard/commit/eb6332cc5c473d6056bd6d9e011017129942ec7d) is unfortunately causing some weirdness where certain pages fail to have any content retrieved when fetched.

'Fetch metadata' is an exception to this, and even causes the feed to fetch normally on the next retrieval, but subsequent retrievals tend to have run into errors.

https://sk-data.special-k.info/repository.json is one such page that exhibits this issue. _(Note that this does not contain data RSS Guard will recognize without post-processing, so a post-processor that dumps all the page content into a new entry is used.)_

I am quite sure that it is that commit causing the issue because:

1. I have a build built from https://github.com/martinrotter/rssguard/commit/45f676713a64b713787c7698a0bd80a9c23f1d95, which is the commit immediately before https://github.com/martinrotter/rssguard/commit/eb6332cc5c473d6056bd6d9e011017129942ec7d, and it's been behaving properly for days
2. I tested this on the build corresponding to https://github.com/martinrotter/rssguard/commit/eb6332cc5c473d6056bd6d9e011017129942ec7d just to isolate it to make sure no other commit that came after was responsible; reproducing the issue doesn't take long

### How to reproduce the bug?

1. Start creating a new feed that points to [this url](https://sk-data.special-k.info/repository.json) and use [this post-processing script](https://github.com/martinrotter/rssguard/files/14515162/TestFeed.txt) (saved as a `.py` file) 
1. Fetch the metadata, press OK to add the new feed
1. Fetch the feed
    * This will be successful
1. Wait 5 seconds
1. Try running the feed again, if successful run 'Cleanup web cache' and then try again
    * You'll eventually have it fail with the error in the section below the next

### What was the expected result?

It should be popping up a new entry corresponding to date and time it was ran with the JSON data.

### What actually happened?

RSS Guard will display this error:
```
Status: error (script threw an error: 'Traceback (most recent call last): File "D:\RSS Guard\data4\TestFeed.py", line 28, in main(input_data) File "D:\RSS Guard\data4\TestFeed.py", line 5, in main json_data = json.loads(input_data) ^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)')
```

### Debug log

Here is two feed retrievals. The first one is successful. I retrieve again 5 seconds later and it fails:

<details>
<summary>Click to view</summary>

```text
time="    98.824" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="    98.824" type="debug" -> core: Displaying messages from feeds IDs: ''274'' and URLs: 'https://sk-data.special-k.info/repository.json'.
time="    98.837" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE Feeds.custom_id IN ('274') AND Messages.is_deleted = 0 AND Messages.is_pdeleted = 0 AND Messages.account_id = 1 ORDER BY Messages.date_created DESC, Messages.is_read ASC, Messages.is_important ASC;'.
time="   100.740" type="debug" -> core: Delaying scheduled feed auto-download for some time since window is focused and updates while focused are disabled by the user and all account caches are empty.
time="   110.736" type="debug" -> core: Delaying scheduled feed auto-download for some time since window is focused and updates while focused are disabled by the user and all account caches are empty.
time="   114.192" type="debug" -> feed-downloader: Starting feed updates from worker in thread '0x591c'.
time="   114.192" type="debug" -> feed-downloader: All caches synchronized.
time="   114.193" type="debug" -> database: SQLite database connection 'db_connection_22812' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   114.195" type="debug" -> feed-downloader: Downloading new messages for feed ID '274' URL: 'https://sk-data.special-k.info/repository.json' title: 'TestFeed' in thread  '18112'.
time="   114.195" type="debug" -> database: SQLite database connection 'db_connection_18112' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   114.195" type="debug" -> core: Downloading URL 'https://sk-data.special-k.info/repository.json' to obtain feed data.
time="   114.196" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   114.448" type="debug" -> network: Destroying Downloader instance.
time="   114.448" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   114.451" type="debug" -> core: We will process feed data with post-process script 'python.exe "TestFeed.py"'.
time="   114.574" type="debug" -> feed-downloader: Downloaded 1 messages for feed ID '274',operation took 379050 microseconds.
time="   114.575" type="debug" -> database: SQLite connection 'db_connection_18112' is already active.
time="   114.575" type="debug" -> database: SQLite database connection 'db_connection_18112' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   114.575" type="debug" -> core: Updating messages in DB.
time="   114.575" type="debug" -> database: Checking if message with title '2024-03-06T14:49:59.546968', url 'https://sk-data.special-k.info'' and author '' is present in DB.
time="   114.598" type="debug" -> database: SQLite connection 'db_connection_18112' is already active.
time="   114.598" type="debug" -> database: SQLite database connection 'db_connection_18112' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   114.600" type="debug" -> database: SQLite connection 'db_connection_18112' is already active.
time="   114.600" type="debug" -> database: SQLite database connection 'db_connection_18112' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   114.602" type="debug" -> database: SQLite connection 'db_connection_18112' is already active.
time="   114.602" type="debug" -> database: SQLite database connection 'db_connection_18112' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   114.604" type="debug" -> database: SQLite connection 'db_connection_18112' is already active.
time="   114.604" type="debug" -> database: SQLite database connection 'db_connection_18112' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   114.605" type="debug" -> database: SQLite connection 'db_connection_18112' is already active.
time="   114.606" type="debug" -> database: SQLite database connection 'db_connection_18112' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   114.606" type="debug" -> feed-downloader: Updating messages in DB took 31620 microseconds.
time="   114.606" type="debug" -> feed-downloader: 1 unread messages and 1 total messages for feed '274' stored in DB.
time="   114.606" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 1/1 (id of feed is 274).
time="   114.609" type="debug" -> feed-downloader: Finished feed updates in thread '0x591c'.
time="   114.632" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="   114.647" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE Feeds.custom_id IN ('274') AND Messages.is_deleted = 0 AND Messages.is_pdeleted = 0 AND Messages.account_id = 1 ORDER BY Messages.date_created DESC, Messages.is_read ASC, Messages.is_important ASC;'.
time="   114.647" type="debug" -> gui: Reloading of msg selections took 15 miliseconds.
time="   120.743" type="debug" -> core: Delaying scheduled feed auto-download for some time since window is focused and updates while focused are disabled by the user and all account caches are empty.
time="   121.119" type="debug" -> feed-downloader: Starting feed updates from worker in thread '0x591c'.
time="   121.119" type="debug" -> feed-downloader: All caches synchronized.
time="   121.119" type="debug" -> database: SQLite connection 'db_connection_22812' is already active.
time="   121.119" type="debug" -> database: SQLite database connection 'db_connection_22812' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   121.119" type="debug" -> feed-downloader: Downloading new messages for feed ID '274' URL: 'https://sk-data.special-k.info/repository.json' title: 'TestFeed' in thread  '25092'.
time="   121.120" type="debug" -> database: SQLite database connection 'db_connection_25092' to file 'D:/RSS Guard/data4/database/database.db' seems to be established.
time="   121.120" type="debug" -> core: Downloading URL 'https://sk-data.special-k.info/repository.json' to obtain feed data.
time="   121.121" type="debug" -> Using ETag value: 'W/"a7be2d43536cd9e45df1d8ae01189259"'.
time="   121.121" type="debug" -> network: Settings of BaseNetworkAccessManager loaded.
time="   121.228" type="debug" -> network: Destroying Downloader instance.
time="   121.228" type="debug" -> network: Destroying SilentNetworkAccessManager instance.
time="   121.231" type="debug" -> core: We will process feed data with post-process script 'python.exe "TestFeed.py"'.
time="   121.331" type="critical" -> core: Post-processing script for feed file failed: 'script threw an error: 'Traceback (most recent call last): File "D:\RSS Guard\data4\TestFeed.py", line 28, in <module> main(input_data) File "D:\RSS Guard\data4\TestFeed.py", line 5, in main json_data = json.loads(input_data) ^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)''.
time="   121.331" type="critical" -> network: Error when fetching feed: 'Feed::Status::OtherError' message: 'script threw an error: 'Traceback (most recent call last): File "D:\RSS Guard\data4\TestFeed.py", line 28, in <module> main(input_data) File "D:\RSS Guard\data4\TestFeed.py", line 5, in main json_data = json.loads(input_data) ^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\python311\Lib\json\decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)''.
time="   121.331" type="debug" -> feed-downloader: Made progress in feed updates, total feeds count 1/1 (id of feed is 274).
time="   121.343" type="debug" -> feed-downloader: Finished feed updates in thread '0x591c'.
time="   121.346" type="debug" -> CTRL is NOT pressed while sorting articles - sorting with standard mode.
time="   121.361" type="debug" -> message-model: Repopulated model, SQL statement is now:
 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE Feeds.custom_id IN ('274') AND Messages.is_deleted = 0 AND Messages.is_pdeleted = 0 AND Messages.account_id = 1 ORDER BY Messages.date_created DESC, Messages.is_read ASC, Messages.is_important ASC;'.
time="   121.361" type="debug" -> gui: Reloading of msg selections took 15 miliseconds.
```
</details><br>

### Operating system and version

* OS: Windows 10 22H2
* RSS Guard version: 4.6.3-eb6332cc5

**Comment by martinrotter** [comment]
I believe I fixed it. Thanks, this was crazy error as I completely forgot to implement part of "etag" feature!

Test with latest devbuild once it compiles. If "etag" was used and URL responds with HTTP/304 (not modified) then RSS Guard prints this in the log:

> time="    39.818" type="warning" -> core:  'https://sk-data.special-k.info/repository.json' reported HTTP/304, meaning that the remote file did not change since last time we checked it.
